### ISSUE TITLE
automatyczne dodanie do HA

### ISSUE THREAD

**Issue by rafi1430** [bonepl/homeassistant-fersktorr-config#1]
@bonepl, czy ja muszę wszystkie zmienne dopisać ręcznie do nowego urządzenia w HA?
Nie można jakoś automatycznie wrzucić tych encji, może jakiś plik z twojego setupu HA?
jestem na początku drogi z HA i tak nie bardzo się poruszam jeszcze w tym 

Rafał

**Comment by bonepl** [comment]
Z tą integracją local tuya niestety wygląda to jak wygląda. Starałem się opisać to w instrukcji na tyle prosto, żeby każdy sobie poradził :). Jak coś jest dla Ciebie niejasne to daj znać, postaram się poprawić.

**Comment by rafi1430** [comment]
@bonepl jest napisana idealnie i prosto ;) , podejmuję rękawicę i tworzę wrócę z opiniami ;)
Dzięki za odp
Rafał

**Comment by rafi1430** [comment]
![Zrzut ekranu 2023-11-02 162024](https://github.com/bonepl/homeassistant-fersktorr-config/assets/79362682/fcee60c3-cfef-4026-9997-7cc01327158a)

**Comment by rafi1430** [comment]
tak to wyszło, czy jest ok?

**Comment by bonepl** [comment]
No to pytanie do Ciebie :) jeżeli działa to zostaje Ci pobawić się wyglądem panelu encji wedle uznania.

**Comment by bonepl** [comment]
Zaktualizowałem trochę instrukcję i dałem przykład mojego panelu z ikonkami
