### ISSUE TITLE
Template config - fersk_torr_status_text

### ISSUE THREAD

**Issue by rafi1430** [bonepl/homeassistant-fersktorr-config#2]
Cześć Kuba,
Pewnie to zabrzmi słabo ale nie mogę sobie poradzić z template

wklei proszę cały code z tablicy pomocników bo cokolwiek nie robię mam cały czas błąd.

switch:
  - platform: template
    switches:
      copy:
      value_template: {%if states.sensor.fersk_torr_status.state == '0' %}
  ok
{%elif states.sensor.fersk_torr_status.state == '8'%}
  tank full
{%else%}
  unknown
{%endif%}

**Comment by bonepl** [comment]
Cześć,

A jaki konkretnie masz błąd?

Ja sobie dodałem template sensor w pomocnikach taki jak w instrukcji:

> {%if states.sensor.fersk_torr_30_status.state == '0' %}ok{%elif states.sensor.fersk_torr_30_status.state == '8'%}tank full{%else%}unknown{%endif%}

Tylko moje encje mają fersk_torr_30_ jako prefix.

**Comment by rafi1430** [comment]
wszystko wpisałem a mimo to mam błędy ?

Sensor None has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)


teraz też mam 30 ale 20 jest dużo cichsze i równie dobrze odbiera wilgoć

**Comment by bonepl** [comment]
U mnie to tak wygląda:

![Screenshot_2023-11-17-20-33-19-02_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/bonepl/homeassistant-fersktorr-config/assets/72575496/ccb07cfd-73fc-4af5-9092-7f55f2e7e25e)


![Screenshot_2023-11-17-20-32-00-31_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/bonepl/homeassistant-fersktorr-config/assets/72575496/bf3155b6-714d-4692-b876-e8d0eda34d21)


![Screenshot_2023-11-17-20-31-00-61_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/bonepl/homeassistant-fersktorr-config/assets/72575496/027b040c-6368-4568-8c14-da3d80c14255)

**Comment by bonepl** [comment]
Jak próbujesz zrobić template sensor przez configuration.yaml to podziel się pełnym fragmentem wpisu. Może być screenshot.

**Comment by rafi1430** [comment]
już wszystko ok, gapa nie zwróciłem uwagi na to 30, już wszystko pokazuje

dzięki
