### ISSUE TITLE
Status 4

### ISSUE THREAD

**Issue by rafi1430** [bonepl/homeassistant-fersktorr-config#3]
Cześć Kuba,

Dopisz do instrukcji Template status '4' , dzisiaj u mnie się załączył ;)

{%if states.sensor.fersk_torr_status.state == '0' %}
  Ok
{%elif states.sensor.fersk_torr_status.state == '4'%}
  Defrost
{%elif states.sensor.fersk_torr_status.state == '8'%}
  Tank full
{%else%}
  unknown
{%endif%}

**Comment by bonepl** [comment]
Dzięki za info, to się automatycznie załącza?

sob., 2 gru 2023, 12:02 użytkownik rafi1430 ***@***.***>
napisał:

**Comment by rafi1430** [comment]
Dzisiaj weszło odtajnienie, jak zamarzł wymiennik to automatycznie załączył.

Odczytałem status z instr i trafiłem na 4 więc szybko dodałem i pokazywało prawidłowo, 
Próbuję jeszcze pozostałe stany wywołać. Jak coś wyjdzie dodam tutaj 😉

Pozdr
